name: Deploy Dashboard

on:
  push:
    branches:
      - trunk
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup_devenv
        name: Setup Devenv
        uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: build_dashboard
        name: Build Dashboard
        uses: ./.github/actions/build-dashboard

      - id: deploy_to_gh_pages
        name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard/public
