---
name: Deploy Dashboard

on:
  push:
    branches:
      - trunk
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy Dashboard
    runs-on: ubuntu-24.04
    steps:
      - id: setup_consumer
        name: Set Up Consumer
        uses: tars-cloud/actions/composite/setup-consumer@822009e983b73316cbf67a3606842502c7be4599 # v3.3.0
        with:
          fetch-depth: 0

      - id: build_dashboard
        name: Build Dashboard
        uses: tars-cloud/actions/composite/run-devenv@822009e983b73316cbf67a3606842502c7be4599 # v3.3.0
        with:
          run: ask dashboard build

      - id: upload_pages_artifact
        name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dashboard/public

      - id: deploy_to_gh_pages
        name: Deploy to GH Pages
        uses: actions/deploy-pages@v5

      - id: report_status
        name: Report Deployment Status
        if: always()
        uses: tars-cloud/actions/composite/report-status@822009e983b73316cbf67a3606842502c7be4599 # v3.3.0
        with:
          title: Deployment Results
          results: |
            build-dashboard=${{ steps.build_dashboard.outcome }}
            deploy-pages=${{ steps.deploy_to_gh_pages.outcome }}
