---
name: Devenv Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: devenv-update
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    name: Update Devenv Dependencies
    uses: tars-cloud/actions/.github/workflows/consumer-devenv-update.yaml@feat/consumer-cargo-crap
    secrets:
      app-id: ${{ secrets.UPDATE_APP_ID || secrets.APP_ID }}
      app-private-key: ${{ secrets.UPDATE_APP_PRIVATE_KEY || secrets.APP_PRIVATE_KEY }}
