---
name: Trivy

on:
  pull_request:
    branches:
      - main
      - trunk
  push:
    branches:
      - main
      - trunk
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: trivy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy:
    name: Trivy Scan
    uses: tars-cloud/actions/.github/workflows/consumer-trivy.yaml@e36c5d93a66a395db6d01c32fdf3c67b6eaca0d2 # v3
    with:
      timeout-minutes: 60
      config-file: auto
